T6940 - Atualizar a versão do FontAwesome/OCA
multidadosti-erp/server-tools pull request #15
Opened 2022-12-28 13:51 UTC by gustotc

# Descrição

Atualiza versão do módulo 'base_fontawesome'

- Atualiza a versão do FontAwesome para 5.3.1

# Informações adicionais

Dados da tarefa: [T6940](https://multi.multidados.tech/web?#id=7349&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)

2022-12-28 15:52 UTC, mstuttgart approved these changes

2022-12-28 15:53 UTC, mstuttgart requested changes

2022-12-28 15:53 UTC, mstuttgart commented on iap_alternative_provider/__manifest__.py
> +    'installable': False,
@gustotc é necessário habilitar a instalação desse modulo?

2022-12-28 15:53 UTC, mstuttgart commented on mail_cleanup/__manifest__.py
> +    'installable': False,
@gustotc é necessário habilitar a instalação desse modulo?

2022-12-28 16:28 UTC, gustotc commented on iap_alternative_provider/__manifest__.py
> +    'installable': False,
Subi sem querer, estava testando pra identificar o erro do runbot e acabei deixando False, voltei ao padrão q estava.

2022-12-28 16:29 UTC, gustotc commented on mail_cleanup/__manifest__.py
> +    'installable': False,
Subi sem querer, estava testando pra identificar o erro do runbot e acabei deixando False, voltei ao padrão q estava.

2022-12-29 12:34 UTC, mstuttgart approved these changes

2022-12-29 12:34 UTC, merged